#!/usr/bin/env bash
# The omarchy source repo and the omarchy-pkgs packaging repo are a matched
# pair. Letting them drift apart produced a 4.0.1 PKGBUILD building 4.0.2
# sources, and the mismatch surfaced only as a pacman file conflict during
# install -- upstream renamed the CUPS override the PKGBUILD moves out of the
# package, so the stale rule missed it and the file collided with `cups`.
source "$(dirname "$0")/../lib.sh"

OMARCHY="${OMARCHY:-$ROOT/../omarchy}"
PKGS="${PKGS_REPO:-$ROOT/../omarchy-pkgs}"
[ -d "$OMARCHY/.git" ] && [ -d "$PKGS/.git" ] || { echo "    skipped: need both checkouts"; exit 0; }

BASE=$(git -C "$OMARCHY" tag --sort=-v:refname | grep -vE '\-?(alpha|beta|rc)[0-9]*$' | head -1)
VER="${BASE#v}"

for pkg in omarchy omarchy-settings; do
  pv=$(grep -m1 '^pkgver=' "$PKGS/pkgbuilds/$pkg/PKGBUILD" 2>/dev/null | cut -d= -f2)
  if [ "$pv" = "$VER" ]; then
    ok "omarchy-pkgs $pkg is at $VER"
  else
    bad "omarchy-pkgs $pkg is at $VER" \
        "PKGBUILD says $pv -- run ./scripts/sync-upstream.sh to update omarchy-pkgs"
  fi
done

# Our patched PKGBUILD is generated; if it lags upstream it is stale.
OURS="$ROOT/pkgbuilds/omarchy/PKGBUILD"
ours_ver=$(grep -m1 '^pkgver=' "$OURS" 2>/dev/null | cut -d= -f2)
if [ "$ours_ver" = "$VER" ]; then
  ok "our patched omarchy PKGBUILD is at $VER"
else
  bad "our patched omarchy PKGBUILD is at $VER" \
      "it says $ours_ver -- run ./scripts/patch-pkgbuild.sh"
fi

# It must be generated, not hand-maintained, or it will drift again.
assert_grep 'generated by scripts/patch-pkgbuild.sh' "$OURS" \
  "our omarchy PKGBUILD is generated, not hand-edited"

# sync-upstream must move both repos together.
assert_grep 'omarchy-pkgs' "$ROOT/scripts/sync-upstream.sh" \
  "sync-upstream also updates the packaging repo"
