#!/usr/bin/env bash
# Regenerate pkgbuilds/omarchy/PKGBUILD from upstream's, with the Pi patch applied.
#
# Keeping a hand-edited copy meant it silently went stale: it stayed at 4.0.1
# while upstream moved to 4.0.2, and the mismatch only surfaced as a file
# conflict during install. Generating it means the patch is a transformation we
# re-apply, not a snapshot we forget to refresh.
set -euo pipefail

cd "$(dirname "$0")/.."
UPSTREAM="${PKGS_REPO:-$PWD/../omarchy-pkgs}/pkgbuilds/omarchy/PKGBUILD"
OUT="pkgbuilds/omarchy/PKGBUILD"

[ -f "$UPSTREAM" ] || { echo "No upstream PKGBUILD at $UPSTREAM" >&2; exit 1; }

python3 - "$UPSTREAM" "$OUT" <<'PY'
import re, sys
src, dst = sys.argv[1], sys.argv[2]
s = open(src).read()

# The Pi boots from its own firmware off a FAT partition and runs an ext4 root,
# so none of the Limine/snapper stack applies. limine-mkinitcpio-hook actively
# fails with "Cannot detect an ESP path" on this layout.
DROP = ('limine', 'limine-mkinitcpio-hook', 'limine-snapper-sync', 'snapper')
removed = []
out = []
for line in s.splitlines(keepends=True):
    m = re.match(r"\s*'([^']+)'\s*$", line)
    if m and m.group(1) in DROP:
        removed.append(m.group(1))
        continue
    out.append(line)
s = ''.join(out)

missing = [d for d in DROP if d not in removed]
if missing:
    sys.exit(f"Expected to remove {missing} from depends but did not find them. "
             "Upstream may have restructured the dependency list -- review by hand.")

marker = ("# omarchy-pi: generated by scripts/patch-pkgbuild.sh from upstream's PKGBUILD.\n"
          "# Do not edit by hand -- rerun the script after syncing omarchy-pkgs.\n"
          "#\n"
          "# Patch applied: the Limine/snapper bootloader stack is dropped from depends.\n"
          "# The Pi boots via its own firmware from a FAT partition with an ext4 root,\n"
          "# so limine-mkinitcpio-hook fails outright and snapper has nothing to snapshot.\n")
s = s.replace("pkgname='omarchy'", marker + "pkgname='omarchy'", 1)
s = s.replace("conflicts=('omarchy-dev')", "conflicts=('omarchy-dev')\nprovides=('omarchy')", 1)

open(dst, 'w').write(s)
print(f"regenerated {dst}: dropped {', '.join(removed)}")
PY

grep -E '^(pkgver|_commit)=' "$OUT" | sed 's/^/  /'
